Store\Checkout\CartItem:
  type: entity
  table: cart_items
  id:
    id:
      type: uuid
      generator: {strategy: NONE}
  fields:
    quantity:
      type: integer
  oneToOne:
    product:
      targetEntity: Store\Catalog\Product
      joinColumn:
        name: product_id
        referencedColumnName: id
  manyToOne:
    cart:
      targetEntity: Cart
      inversedBy: products
      joinColumn:
        name: cart_id
        referencedColumnName: id

