# Project language
language: php

# Allows use container-based infrastructure
sudo: required

# Start mysql service
services:
  - docker

# Cache composer packages so "composer install" is faster
cache:
  directories:
    - $HOME/.composer/cache/files

# Matrix to test in every php version
matrix:
  # Fast finish allows to set the build as "finished" even if the "allow_failures" matrix elements are not finished yet.
  fast_finish: true
  include:
    - php: 7.1

# Define an environment variable
env:
  - SYMFONY_VERSION="3.0.*" DB=mysql

before_install:
  - npm install -g dredd

# Install composer dependencies,
install:
  - cp app/config/parameters.yml.dist app/config/parameters.yml
  - cd docker2
  - cp .env.travis .env
  - make -k install
  - cd ..


before_script:
  - dredd --language=vendor/bin/dredd-hooks-php --hookfiles=./hooks*.php

# Run script
script:
  - vendor/bin/phpspec run

# After a build, send email notification with the build results
notifications:
  email: mieszkomalawski@gmail.com