catalog:
    type: rest
    prefix: /api/catalog
    resource: AppBundle\Controller\Catalog\ProductController

checkout:
    type: rest
    prefix: /api/checkout
    resource: AppBundle\Controller\Checkout\CartController

#NelmioApiDocBundle:
#    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
#    prefix:   /api/doc