catalog:
    type: rest
    prefix: /api/catalog
    resource: AppBundle\Controller\Catalog\ProductController

#NelmioApiDocBundle:
#    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
#    prefix:   /api/doc