Store\Catalog\Product:
  type: entity
  table: products
  repositoryClass: AppBundle\Repository\ProductRepository
  id:
    id:
      type: uuid
      generator: {strategy: NONE}
  embedded:
    price:
      class: Money\Money
      columnPrefix: false
  fields:
    name:
      type: string
      length: 255
    priority:
      type: integer
